export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const MESSAGES_LOADED = "MESSAGES_LOADED";
export const MESSAGES_ERROR = "MESSAGES_ERROR";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const ALL_MESSAGES = "ALL_MESSAGES";
export const SENDING_FILE = "SENDING_FILE";
export const END_SENDING_FILE = "END_SENDING_FILE";
export const NEW_REACTION_MESSAGE = "NEW_REACTION_MESSAGE";
export const ALREADY_REACTED_MESSAGE = "ALREADY_REACTED_MESSAGE";
export const WAITING_REACTION_MESSAGE = "WAITING_REACTION_MESSAGE";

export const CREATE_ALERT = "CREATE_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GROUPS_LOADED = "GROUPS_LOADED";
export const GROUPS_LOADING = "GROUPS_LOADING";
export const GROUPS_ERROR = "GROUPS_ERROR";
export const GROUPS_LOGOUT = "GROUPS_LOGOUT";
export const GROUP_CREATED = "GROUP_CREATED";
export const GROUP_CHOSEN = "GROUP_CHOSEN";
export const GROUP_USERS_LOADED = "GROUP_USERS_LOADED";
export const ADD_TO_GROUP_ERROR = "ADD_TO_GROUP_ERROR";

export const CHANNEL_CHOSEN = "CHANNEL_CHOSEN";
